Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/focal64"
 config.vm.network "forwarded_port", guest: 80, host: 8080
 config.vm.network "public_network"
 config.vm.synced_folder "./docker/", "/tmp/docker/"
  
 config.vm.provision "shell", inline: <<-SHELL
    sudo apt -y remove docker docker-engine docker.io containerd runc
version: '3.8'
sudo apt update
sudo apt install net-tools
    sudo apt -y install ca-certificates curl gnupg lsb-release
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt update
    sudo apt -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
    sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo mkdir site
    sudo docker container run -d --name docker-nginx -p 80:80 -v /home/vagrant/site:/var/www/html nginx
    sudo docker container ps
   
   
  SHELL
  

end
